import os


#cleaning mp3 files generated by weather app
for root,dir,files in os.walk(os.getcwd()):
    for file in files:
        if file.endswith('mp3'):
            os.remove(file)
print('operation completed')